core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'))
]

index/urls.py
from django.urls import path
from index import views

urlpatterns = [
    path('', views.ResultIndex, name='home'),
    path('lga/', views.get_lga, name='get_LGA'),
    path('Party-result/', views.PartyIndex, name='PartyResult'),
    path('add-party-result/', views.addPartyResult, name='apres')
]

index/models.py
from django.db import models

# Create your models here.
class AgentName(models.Model):
    firstname = models.CharField(max_length=255, null=False)
    lastname = models.CharField(max_length=255, null=False)
    email = models.CharField(default="", max_length=255, null=False)
    phone = models.CharField(max_length=13, null=False)
    pollingunit_uniqueid = models.UUIDField()

    def __str__(self):
        return str(self.firstname)

class Announced_lga_results(models.Model):
    lga_name = models.CharField(default="", max_length=50, null=False)
    party_abbreviation = models.CharField(default="", max_length=4, null=False)
    party_score = models.IntegerField(null=False)
    entered_by_user = models.CharField(default="", max_length=50, null=False)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=False)

    def __str__(self):
        return str(f'{self.lga_name} {self.entered_by_user}')

class Announced_pu_results(models.Model):
    polling_unit_uniqueid = models.CharField(default="", max_length=50, null=True)
    party_abbreviation = models.CharField(default="", max_length=4, null=True)
    party_score = models.IntegerField(null=True)
    entered_by_user = models.CharField(default="", max_length=50, null=True)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=True)

    def __str__(self):
        return str(f'{self.party_abbreviation} {self.polling_unit_uniqueid}')

class Announced_state_results(models.Model):
    state_name = models.CharField(default="", max_length=50, null=True)
    party_abbreviation = models.CharField(default="", max_length=4, null=True)
    party_score = models.IntegerField(null=True)
    entered_by_user = models.CharField(default="", max_length=50, null=True)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=True)

    def __str__(self):
        return str({self.state_name})

class Announced_ward_results(models.Model):
    ward_name = models.CharField(default="", max_length=50, null=True)
    party_abbreviation = models.CharField(default="", max_length=4, null=True)
    party_score = models.IntegerField(null=True)
    entered_by_user = models.CharField(default="", max_length=50, null=True)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=True)

    def __str__(self):
        return str({self.ward_name})

class LGA(models.Model):
    lga_id = models.IntegerField(null=True)
    lga_name = models.CharField(default="", max_length=50, null=True)
    state_id = models.IntegerField(null=True)
    lga_description = models.TextField(default="", max_length=255, null=True)
    entered_by_user = models.CharField(default="", max_length=50, null=True)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=True)

    def __str__(self):
        return str(self.lga_name)

class Party(models.Model):
    partyid = models.CharField(max_length=11, null=True)
    partyname = models.CharField(max_length=11, null=True)

class Polling_unit(models.Model):
    polling_unit_id = models.IntegerField(null=True)
    ward_id = models.IntegerField(null=True)
    lga_id = models.IntegerField(null=True, blank=True)
    uniquewardid = models.IntegerField(null=True)
    polling_unit_number = models.CharField(default="", max_length=50, null=True)
    # polling_unit_number = models.CharField(default="", max_length=50, null=True)
    polling_unit_name = models.CharField(default="", max_length=50, null=True)
    polling_unit_description = models.TextField(default="")
    lat = models.CharField(default="", max_length=255,null=True)
    long = models.CharField(default="", max_length=255,null=True)
    entered_by_user = models.CharField(default="", max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50)

    def __str__(self):
        return str(self.lga_id)

class States(models.Model):
    state_name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.state_name)

class Ward(models.Model):
    ward_id = models.IntegerField(null=True)
    ward_name = models.CharField(max_length=50, null=True)
    lga_id = models.IntegerField(null=True)
    ward_description = models.TextField(default="")
    entered_by_user = models.CharField(default="", max_length=50)
    date_entered = models.DateTimeField()
    user_ip_address = models.CharField(default="", max_length=50, null=True)

    def __str__(self):
        return str(self.ward_name)

index/forms.py
from django import forms
from .models import *

class Announced_pu_results_form(forms.ModelForm):
    class Meta:
        model = Announced_pu_results
        fields = "__all__"

index/views.py
from django.http import HttpResponse, JsonResponse
import datetime
from django.shortcuts import render
from .models import *
from .forms import *

# Create your views here.
def ResultIndex(request):
    polling_obj = Polling_unit.objects.all()[:1]
    lga_obj = LGA.objects.all()
    context = {
        'data':polling_obj,
        'lga_data': lga_obj
    }
    return render(request, 'index.html', context)

def get_lga(request):
    if request.method == 'POST':
        choice =request.POST.get('user_choice')
        choice = int(choice)
        obj = Polling_unit.objects.filter(lga_id=choice)
        return JsonResponse({'data': len(obj)})


def PartyIndex(request, *args, **kwargs):
    form = Announced_pu_results_form
    party_results = Announced_pu_results.objects.all()
    context = {
        'form':form,
         'party_data': party_results
    }
    return render(request, 'party_result.html', context)

def addPartyResult(request):
    if request.method == "POST":
        id_data = request.POST.get('puu')
        party_abbr = request.POST.get('pa')
        party_score_data = request.POST.get('ps')
        user = request.POST.get('user')
        date = datetime.datetime.now()
        ipaddr = request.POST.get('ipadd')
        create_result = Announced_pu_results.objects.create(
            polling_unit_uniqueid = id_data,
            party_abbreviation = party_abbr,
            party_score=party_score_data,
            entered_by_user = user,
            date_entered = date,
            user_ip_address = ipaddr
        )
        create_result.save()
        success = f'Result added successfully for {party_abbr} by {user} on {date.date()}'
    return HttpResponse(success)

templates/example2.html
{%extends 'overlord.html' %}
{%block title%}
Something
{%endblock title%}
<!--  -->
{%block links%}
<style>
body, html{
  height: 0% !important;
}

.modalCont{
  animation: 3s slideout;
  position: fixed;
  right: 0;
  left: 0;
  transform: translateY(-572px);
  background: #f4f4f4;
}

.triggerin {
    position: fixed;
    bottom: 0;
}
.display-modal{
  animation: 1.9s slidein;
  position: fixed;
  left: 0;
  right: 0;
  z-index: 10;
  background: #f4f4f4;
}

.text-end{
  cursor: pointer;
}

@keyframes slidein{
  from{
    transform: translateY(-572px);
  }
  to{
    transform: translateY(0px);
  }
}


@keyframes slideout{
  from{
    transform: translateY(0px);
  }
  to{
    transform: translateY(-568px);
  }
}

input:focus{
  border: 1px solid #c0bbbb !important;
}
</style>
{%endblock links%}
<!--  -->
{%block contents%}
  <div class="container-sm border mt-3 modalCont" id="inner-cont">
    <div class="text-end" id="close-cont" style="transform: rotateX(45deg);">
      <h4>X</h4>
    </div>
    <form class="ui form container px-3 py-1 mb-2" method="POST">
      {%csrf_token%}
      <div class="ui dividing header mt-1">Party Results</div>
      <div class="field">
        {{form.as_p}}
      </div>
        <button type="submit" class="ui button">Submit</button>
      </form>
  </div>
<section>
  <section class="container py-3 mt-2">
    <div class="data-container text-center">
        <h1 class="p-part display-5">
            Polling Unit Party Results
        </h1>
    </div>
    {%csrf_token%}
    <div class="mt-3">
        <div class="">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <!-- <th scope="col">LGA</th> -->
                  <th scope="col">Polling Unit uniqueid</th>
                  <th scope="col">Party abbreviation</th>
                  <th scope="col">Party Score</th>
                  <th scope="col">User</th>
                  <th scope="col">Date</th>
                  <th scope="col">IPAddress</th>
                </tr></thead>
                <tbody>
                  {%for obj in party_data%}
                  <tr>
                    <td class="table-data">
                      {{obj.polling_unit_uniqueid}}
                    </td>
                    <td class="table-data">
                      {{obj.party_abbreviation}}
                    </td>
                    <td class="table-data">
                      {{obj.party_score}}
                    </td>
                    <td class="table-data">
                      {{obj.entered_by_user}}
                    </td>
                    <td class="table-data">
                      {{obj.date_entered}}
                    </td>
                    <td class="table-data">
                      {{obj.user_ip_address}}
                    </td>
                  </tr>
                  {%endfor%}
                </tbody>
              </table>
        </div>
    </div>
</section>
</section>
<div class="my-4 px-2 triggerin">
  <button class="ui button black" id="addRes">Add</button>
</div>
{%endblock contents%}
<!-- JS scripts -->
{%block scripts%}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  let  TriggerButton = document.getElementById('addRes')
  let  modalContainer = document.getElementById('inner-cont')
  let  CloseButton = document.getElementById('close-cont')
  TriggerButton.addEventListener('click', () => {
    if(modalContainer.classList.contains('modalCont')){
      modalContainer.classList.remove('modalCont')
      modalContainer.classList.add('display-modal')
      TriggerButton.classList.add('d-none')
    }
  })

  CloseButton.addEventListener('click', () => {
    if(modalContainer.classList.contains('display-modal')){
      modalContainer.classList.remove('display-modal')
      modalContainer.classList.add('modalCont')
      TriggerButton.classList.remove('d-none')
    }
  })

</script>

{%endblock scripts%}

templates/index.html
{%extends 'overlord.html' %}
{%block title%}
Results
{%endblock title%}
<!--  -->
{%block contents%}
    <div class="data-container text-center">
        <h1 class="p-part display-5">
            Polling Unit Result
        </h1>
    </div>
<!--  -->
<!-- <section class=""> -->
    <div class="container-sm table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Polling unit id</th>
                    <th scope="col">LGA ID</th>
                    <th scope="col">Unique Ward ID</th>
                    <th scope="col">PUID</th>
                    <th scope="col">PUName</th>
                    <th scope="col">POD</th>
                    <th scope="col">Latitude</th>
                    <th scope="col">Longitude</th>
                    <th scope="col">Entered User</th>
                    <th scope="col">Added</th>
                    <th scope="col">IPAddress</th>
                </tr>
            </thead>
            <tbody>
                {%for i in data%}
              <tr>
                <td>{{i.id}}</td>
                <td>{{i.polling_unit_id}}</td>
                <td >{{i.lga_id}}</td>
                <td>{{i.uniquewardid}}</td>
                <td>{{i.polling_unit_number}}</td>
                <td>{{i.polling_unit_name}}</td>
                <td>{{i.polling_unit_description}}</td>
                <td>{{i.lat}}</td>
                <td>{{i.long}}</td>
                <td>{{i.entered_user}}</td>
                <td>{{i.date_entered}}</td>
                <td>{{i.user_ip_address}}</td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
    </div>
    <!-- </section> -->

<section class="container py-3 mt-2">
    <div class="data-container text-center">
        <h1 class="p-part display-5">
            Sum Total for LGA
        </h1>
    </div>
    {%csrf_token%}
    <div class="mt-3">
        <div class="">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col">LGA</th>
                  <th scope="col">Total of polling points</th>
                </tr></thead>
                <tbody>
                  <tr>
                    <td>
                        <select class="form-control form-control-sm" id="lga-select">
                            <option>Select LGA</option>
                            {%for lga in lga_data%}
                            <option value="{{lga.id}}">{{lga.lga_name}}</option>
                            {%endfor%}
                        </select>
                    </td>
                    <td id="table-sum"></td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div>
</section>
{%endblock contents%}
<!-- JS scripts -->
{%block scripts%}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    console.log($('#lga-select').val());
    $(document).on('change', '#lga-select', () => {
        $.ajax({
            type:"POST",
            url:'lga/',
            data:{
                user_choice: $('#lga-select').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(results){
                $('#table-sum').empty();
                $('#table-sum').append(results.data);
            }
        })
    })
</script>
{%endblock scripts%}

templates/overlord.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css" integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--  Semantic-UI Table CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/components/table.min.css" integrity="sha512-LO7R36eoQTR8mctOTFrAUUGCBiqbouo0mzi5dicyVrW76ECJSI4leeTh3PIX4Hp+09++NA3TVFPRg/0C7viORA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--  Bootestrap CDN-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- jQuery CDN-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.js" integrity="sha512-CX7sDOp7UTAq+i1FYIlf9Uo27x4os+kGeoT7rgwvY+4dmjqV0IuE/Bl5hVsjnQPQiTOhAX1O2r2j5bjsFBvv/A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {%block links%}

    {%endblock links%}
    <title>{%block title%}Bincom{%endblock title%}</title>
</head>
<style>
    body{
        box-sizing: border-box;
        margin:0px;
        padding: 0px;
        background-color: #737373/10%;
    }
    li{
        list-style: none;
    }
    .data-container{
        margin: auto;
        padding: 1.5rem 0.5rem;
    }
    .data-container ul{
        display: flex;
        align-items: center;
        justify-content: space-evenly;
    }
    li .p-party{
        font-weight: bolder;
        font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
        font-size: .9rem;
    }
    #lga-select:focus{
        border: 3px solid #737373 !important;
        box-shadow: 10% 10% #ec3939 !important;
    }
</style>
<body>
{%block contents%}

{%endblock contents%}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<!--  -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<!--  -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!--  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js" integrity="sha512-Xo0Jh8MsOn72LGV8kU5LsclG7SUzJsWGhXbWcYs2MAmChkQzwiW/yTQwdJ8w6UA9C6EVG18GHb/TrYpYCjyAQw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{%block scripts%}
<script>
    console.log($('#lga-select').val());
    $(document).on('change', '#lga-select', () => {
        $.ajax({
            type:"POST",
            url:'lga/',
            data:{
                user_choice: $('#lga-select').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(results){
                $('#table-sum').empty();
                $('#table-sum').append(results.data);
            }
        })
    })
</script>
{%endblock scripts%}
</body>
</html>

templates/party_result.html
{%extends 'overlord.html' %}
{%block title%}
Something
{%endblock title%}
<!--  -->
{%block links%}
<style>
body, html{
  height: 0% !important;
}

.modalCont{
  animation: 3s slideout;
  position: fixed;
  right: 0;
  left: 0;
  transform: translateY(-619px);
  background: #f4f4f4;
}

.triggerin {
    position: fixed;
    bottom: 0;
}
.display-modal{
  animation: 1.9s slidein;
  position: fixed;
  left: 0;
  right: 0;
  z-index: 10;
  background: #f4f4f4;
}

.text-end{
  cursor: pointer;
}

@keyframes slidein{
  from{
    transform: translateY(-619px);
  }
  to{
    transform: translateY(0px);
  }
}


@keyframes slideout{
  from{
    transform: translateY(0px);
  }
  to{
    transform: translateY(-619px);
  }
}

input:focus{
  border: 1px solid #c0bbbb !important;
}
</style>
{%endblock links%}
<!--  -->
{%block contents%}
  <div class="container-sm border mt-3 modalCont" id="inner-cont">
    <div class="text-end" id="close-cont" style="transform: rotateX(45deg);">
      <h4>X</h4>
    </div>
    <form class="ui form container px-3 py-1 mb-2" method="POST" id="result-form">
      {%csrf_token%}
      <div class="ui dividing header mt-1">Party Results</div>
      <div class="field">
        {{form.as_p}}
      </div>
        <button type="submit" class="ui button">Submit</button>
      </form>
      <div class="container message py-2">
        <h3 class="text-center text-center fw-bolder fs-6 text-success" id="mssgtext"></h3>
      </div>
  </div>
<section>
  <section class="container py-3 mt-2">
    <div class="data-container text-center">
        <h1 class="p-part display-5">
            Polling Unit Party Results
        </h1>
    </div>
    <!--  -->
    <div class="mt-3">
        <div class="">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <!-- <th scope="col">LGA</th> -->
                  <th scope="col">Polling Unit uniqueid</th>
                  <th scope="col">Party abbreviation</th>
                  <th scope="col">Party Score</th>
                  <th scope="col">User</th>
                  <th scope="col">Date</th>
                  <th scope="col">IPAddress</th>
                </tr></thead>
                <tbody>
                  {%for obj in party_data%}
                  <tr>
                    <td class="table-data">
                      {{obj.polling_unit_uniqueid}}
                    </td>
                    <td class="table-data">
                      {{obj.party_abbreviation}}
                    </td>
                    <td class="table-data">
                      {{obj.party_score}}
                    </td>
                    <td class="table-data">
                      {{obj.entered_by_user}}
                    </td>
                    <td class="table-data">
                      {{obj.date_entered}}
                    </td>
                    <td class="table-data">
                      {{obj.user_ip_address}}
                    </td>
                  </tr>
                  {%endfor%}
                </tbody>
              </table>
        </div>
    </div>
</section>
</section>
<div class="my-4 px-2 triggerin">
  <button class="ui button black" id="addRes">Add</button>
</div>
{%endblock contents%}
<!-- JS scripts -->
{%block scripts%}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  let  TriggerButton = document.getElementById('addRes')
  let  modalContainer = document.getElementById('inner-cont')
  let  CloseButton = document.getElementById('close-cont')
  TriggerButton.addEventListener('click', () => {
    if(modalContainer.classList.contains('modalCont')){
      modalContainer.classList.remove('modalCont')
      modalContainer.classList.add('display-modal')
      TriggerButton.classList.add('d-none')
    }
  })

  CloseButton.addEventListener('click', () => {
    if(modalContainer.classList.contains('display-modal')){
      modalContainer.classList.remove('display-modal')
      modalContainer.classList.add('modalCont')
      TriggerButton.classList.remove('d-none')
    }
  })
  // End of modal magik

  // Result form & data submission to server
    $(document).on('submit', '#result-form', (e) => {
      e.preventDefault();
      $.ajax({
          type:"POST",
          url:'{%url "apres" %}',
          data:{
              puu: $('#id_polling_unit_uniqueid').val(),
              pa: $('#id_party_abbreviation').val(),
              ps: $('#id_party_score').val(),
              user: $('#id_entered_by_user').val(),
              date: $('id_date_entered').val(),
              ipadd: $('#id_user_ip_address').val(),
              csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
          },
          success: function(response){
            // $('input:number').val(0);
            $('#mssgtext').empty();
            $('#mssgtext').append(response);
            $('#result-form')[0].reset();
          }
      })
    })

</script>

{%endblock scripts%}